### ISSUE TITLE
I keep receiving `:gun_down` and `:gun_up` error messages

### ISSUE THREAD

**Issue by ospaarmann** [ospaarmann/exdgraph#15]
I am using exdgraph to build a little side project. It is a phoenix app inside an umbrella app. When running the phoenix server the messages `:gun_down` and `:gun_up` keep popping up in my log every couple of seconds. It seems as if the connection breaks every couple of seconds and gun then re-connects. Since I use the default settings of a pool of 5 connections and I receive 5 errors it looks like the whole pool disconnects.

[The gun docs state: ](https://github.com/ninenines/gun/blob/104ef37f1869616b7b2d0a303838fc4562a1b7b6/doc/src/guide/connect.asciidoc)

> When the connection is lost, Gun will send a gun_down message indicating the current protocol, the reason the connection was lost and two list of stream references.
> 
> The first list indicates open streams that may have been processed by the server. The second list indicates open streams that the server did not process.
> 

I could also handle these messages on my side but I first want to figure out what is going on. I created a feature branch that handles the messages but doesn't solve the issue: https://github.com/ospaarmann/exdgraph/tree/fix_gun_error

```
[error] ExDgraph.Protocol #PID<0.280.0> received unexpected message: {:gun_down, #PID<0.288.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.279.0> received unexpected message: {:gun_down, #PID<0.287.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.278.0> received unexpected message: {:gun_down, #PID<0.286.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.276.0> received unexpected message: {:gun_down, #PID<0.284.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.277.0> received unexpected message: {:gun_down, #PID<0.285.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.280.0> received unexpected message: {:gun_up, #PID<0.288.0>, :http2}
[error] ExDgraph.Protocol #PID<0.279.0> received unexpected message: {:gun_up, #PID<0.287.0>, :http2}
[error] ExDgraph.Protocol #PID<0.277.0> received unexpected message: {:gun_up, #PID<0.285.0>, :http2}
[error] ExDgraph.Protocol #PID<0.276.0> received unexpected message: {:gun_up, #PID<0.284.0>, :http2}
[error] ExDgraph.Protocol #PID<0.278.0> received unexpected message: {:gun_up, #PID<0.286.0>, :http2}
[error] ExDgraph.Protocol #PID<0.280.0> received unexpected message: {:gun_down, #PID<0.288.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.279.0> received unexpected message: {:gun_down, #PID<0.287.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.276.0> received unexpected message: {:gun_down, #PID<0.284.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.278.0> received unexpected message: {:gun_down, #PID<0.286.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.277.0> received unexpected message: {:gun_down, #PID<0.285.0>, :http2, :normal, [], []}
[error] ExDgraph.Protocol #PID<0.280.0> received unexpected message: {:gun_up, #PID<0.288.0>, :http2}
[error] ExDgraph.Protocol #PID<0.278.0> received unexpected message: {:gun_up, #PID<0.286.0>, :http2}
[error] ExDgraph.Protocol #PID<0.276.0> received unexpected message: {:gun_up, #PID<0.284.0>, :http2}
[error] ExDgraph.Protocol #PID<0.279.0> received unexpected message: {:gun_up, #PID<0.287.0>, :http2}
[error] ExDgraph.Protocol #PID<0.277.0> received unexpected message: {:gun_up, #PID<0.285.0>, :http2}
```

**Help is wanted**. As of now it isn't clear where this issue comes from since I had too little time to investigate.

**Comment by yatender-oktalk** [comment]
same happening with me
```
18:22:27.213 [error] ExDgraph.Protocol #PID<0.224.0> received unexpected message: {:gun_down, #PID<0.229.0>, :http2, :normal, [], []}

18:22:27.213 [error] ExDgraph.Protocol #PID<0.225.0> received unexpected message: {:gun_down, #PID<0.230.0>, :http2, :normal, [], []}

18:22:27.214 [error] ExDgraph.Protocol #PID<0.226.0> received unexpected message: {:gun_down, #PID<0.231.0>, :http2, :normal, [], []}

18:22:27.214 [error] ExDgraph.Protocol #PID<0.223.0> received unexpected message: {:gun_down, #PID<0.228.0>, :http2, :normal, [], []}

18:22:27.214 [error] ExDgraph.Protocol #PID<0.222.0> received unexpected message: {:gun_down, #PID<0.232.0>, :http2, :normal, [], []}
```

**Comment by ospaarmann** [comment]
@yatender-oktalk I have a **temporary** fix up here: https://github.com/ospaarmann/exdgraph/tree/fix_gun_error

This "fix" just prevents the error messages from polluting your console. I am working on a real fix right now but this seems to be quite deep down the rabbit hole ex_dgraph -> grpc -> gun...

🐇

**Comment by ospaarmann** [comment]
I profiled gun and gun_http2 to see what is going on. Server is dropping the connection with `{goaway,0,enhance_your_calm,<<"too_many_pings">>}`.

That means the `keepalive` value for gun needs to be increased. 5000ms between pings seems to be too little. 

This is atm not configurable in grpc-elixir (which is using gun). I will submit a pull request to pass configuration for Gun directly into the grpc-elixir config. Hard to say how quickly this will be accepted.

Full trace can be found here: https://gist.github.com/ospaarmann/c592fa984f775810b2698bf0b4d82228

**Comment by ospaarmann** [comment]
I released alpha.5 to fix this issue for now @yatender-oktalk. 

👉https://github.com/ospaarmann/exdgraph/releases/tag/v0.2.0-alpha.5
👉https://hex.pm/packages/ex_dgraph/0.2.0-alpha.5

It seems to be a bug in grpc itself which was possibly introduced in v1.8.x and fixed in v1.8.4. It looks like the current version of Dgraph still uses grpc 1.8.2. I opened an issue in Dgraph to address this bug:

👉https://github.com/dgraph-io/dgraph/issues/2444

Will keep you updated. But using the latest version of ExDgraph will at least get rid of the messages and improve performance.

**Comment by yatender-oktalk** [comment]
Thank you so much.

**Comment by emhagman** [comment]
I am still receiving the messages on the latest alpha stated above.
```
2018-08-23T16:22:15.979399+00:00 app[web.1]: 16:22:15.979 [error] ExDgraph.Protocol #PID<0.361.0> received unexpected message: {:gun_down, #PID<0.382.0>, :http2, :normal, [], []}
2018-08-23T16:22:15.981673+00:00 app[web.1]: 16:22:15.979 [error] ExDgraph.Protocol #PID<0.370.0> received unexpected message: {:gun_down, #PID<0.376.0>, :http2, :normal, [], []}
2018-08-23T16:22:17.826791+00:00 app[web.1]: 16:22:17.826 [error] ExDgraph.Protocol #PID<0.369.0> received unexpected message: {:gun_down, #PID<0.383.0>, :http2, :normal, [], []}
2018-08-23T16:22:17.844966+00:00 app[web.1]: 16:22:17.844 [error] ExDgraph.Protocol #PID<0.367.0> received unexpected message: {:gun_down, #PID<0.378.0>, :http2, :normal, [], []}
2018-08-23T16:22:21.019682+00:00 app[web.1]: 16:22:21.019 [error] ExDgraph.Protocol #PID<0.361.0> received unexpected message: {:gun_up, #PID<0.382.0>, :http2}
2018-08-23T16:22:21.075397+00:00 app[web.1]: 16:22:21.075 [error] ExDgraph.Protocol #PID<0.370.0> received unexpected message: {:gun_up, #PID<0.376.0>, :http2}
2018-08-23T16:22:23.007516+00:00 app[web.1]: 16:22:23.007 [error] ExDgraph.Protocol #PID<0.367.0> received unexpected message: {:gun_up, #PID<0.378.0>, :http2}
2018-08-23T16:22:23.084680+00:00 app[web.1]: 16:22:23.084 [error] ExDgraph.Protocol #PID<0.369.0> received unexpected message: {:gun_up, #PID<0.383.0>, :http2}
```

I understand that this is on Dgraph but I thought you were hiding the messages?

**Comment by emhagman** [comment]
I submitted a PR for now to just catch the messages and log them at the debug level. Almost exactly the same as your branch but with added logging.

https://github.com/ospaarmann/exdgraph/pull/17

**Comment by ospaarmann** [comment]
Fixed with https://github.com/ospaarmann/exdgraph/releases/tag/v0.2.0-beta.3

@emhagman
